id: formular.test.ig
canonical: http://example.org/fhir/test-formular-ig
name: TestImplementationGuide
title: Test Implementation Guide
description: A test implementation guide for validating the local FHIR IG Publisher environment
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: STU1
license: CC0-1.0
publisher: Test Organization

applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Index
  Akteure.md:
    title: Akteure
  Begriffsdefinitionen.md:
    title: Begriffsdefinitionen
  Beispielszenarien.md:
    title: Beispielszenarien
  BestPractice.md:
    title: Best Practice
  FormularDatenExtraktion.md:
    title: Formular Daten Extraktion
  FormularDatenQuelle.md:
    title: Formular Daten Quelle
  FormularDatenRueckuebermittlung.md:
    title: Formular Daten Rückübermittlung
  FormularDatenValidierung.md:
    title: Formular Daten Validierung
  FormularDatenVorbelegung.md:
    title: Formular Daten Vorbelegung
  FormularDefinitionsErsteller.md:
    title: Formular Definitions Ersteller
  FormularDefinitionsVerwalter.md:
    title: Formular Definitions Verwalter
  FormularDefinitionsVerwaltung.md:
    title: Formular Definitions Verwaltung
  FormularLauncher.md:
    title: Formular Launcher
  FormularRenderer.md:
    title: Formular Renderer
  FormularRendering.md:
    title: Formular Rendering
  Kompatibilitaet.md:
    title: Kompatibilität
  Launch.md:
    title: Launch
  ReleaseNotes.md:
    title: Release Notes
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen
  UebergreifendeFestlegungenIndex.md:
    title: Übergreifende Festlegungen Index
  uml.md:
    title: UML
  Ziele.md:
    title: Ziele


menu:
  Index: index.html
  Release Notes: ReleaseNotes.html
  Ziele: Ziele.html
  Spezifikation:
    Akteure: Akteure.html
    Formular Definitions Ersteller: FormularDefinitionsErsteller.html
    Formular Definitions Verwalter: FormularDefinitionsVerwalter.html
    Formular Definitions Verwaltung: FormularDefinitionsVerwaltung.html
    Formular Launcher: FormularLauncher.html
    Launch: Launch.html
    Formular Renderer: FormularRenderer.html
    Formular Rendering: FormularRendering.html
    Formular Daten Quelle: FormularDatenQuelle.html
    Formular Daten Vorbelegung: FormularDatenVorbelegung.html
    Formular Daten Validierung: FormularDatenValidierung.html
    Formular Daten Extraktion: FormularDatenExtraktion.html
    Formular Daten Rückübermittlung: FormularDatenRueckuebermittlung.html
    Beispielszenarien: Beispielszenarien.html
    Best Practice: BestPractice.html
    Begriffsdefinitionen: Begriffsdefinitionen.html
  Festlegungen:
    Übergreifende Festlegungen Index: UebergreifendeFestlegungenIndex.html
    Übergreifende Festlegungen: UebergreifendeFestlegungen.html
    Kompatibilität: Kompatibilitaet.html
  FHIR-Artefakte:
    Artefakte: artifacts.html
    CapabilityStatements: capabilitystatements.html
    Profile: profiles.html
    Terminology: terminology.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true