@startuml

actor Buchende
participant "Termin-Requestor (Patientenportal)" as TR
participant "IDP (Identitätsprovider)" as IDP
participant "Termin-Repository" as TRP
participant "MPI (Master Patient Index)" as MPI
participant "BasisServer" as BS

Note right of Buchende: Es kann sich sowohl um Patienten als auch um angehörige Personen handeln, \n die einen Termin buchen möchten. \n\nDer Buchende kann auch ein Gastzugang sein, \n der keine Identität verifizieren muss.

Buchende-->>TR: Aufruf in GUI und Auswahl
TR -> TRP: Anfrage verfügbare Termine für Fachbereich
TRP -> TR: Rückgabe verfügbarer Termine

TR -> Buchende: Visualisierung der verfügbaren Termine

Buchende->>TR: Auswahl eines Termins

TR -> TR: Erstellen des Termins (vorläufig)
TR -> Buchende: Bestätigung im Portal (ggf. per E-Mail/SMS)
Note right of TR: Termin im Frontend geblockt, aber weder gebucht,  noch mit Patientendaten verknüpft

Buchende-->>TR: ggf. Schnelleingabe Patienten Identität (z.B. gID, KVNR)
TR-->>IDP: ggf. Identify Patient Request (z. B. gID, KVNR)
IDP-->>TR: ggf. Identify Patient (validierte Identität, KVNR)

TR-->>Buchende: ggf. Zeige dem Buchenden nach der Identifikation an, ob und welche Daten bereits vorliegen, \n und biete die Möglichkeit zur Korrektur/Ergänzung.
Buchende-->>TR: ggf. Korrektur/Ergänzung der Patientendaten
Note right of TR: ggf. Identität verifiziert

Buchende->>TR: ggf. Registrierung mit Name, Geburtsdatum, Adresse, Versicherung \n (kann entfallen bei Schnelleingabe - s.o. - , bzw bei Gastzugang)
Buchende-->>TR: (Falls Buchende nicht Patient ist: Angaben zum Patienten)

TR -> MPI: Lookup / GET Patientendaten zur Verknüpfung (basierend auf KVNR)- ggf. nur als Referenz
MPI -> MPI: Match Patient
MPI -> BS: GET Patientendaten
BS -> MPI: Rückgabe Patientendaten
MPI -> TR: Patientendaten zurückliefern

TR -> BS: GET Patientendaten 
BS -> TR: Rückgabe Patientendaten - als ISiK konformes Profil

TR -> TR: Verknüpfung des Termins mit Patientendaten - als ISiK konformes Profil

TR -> TRP: Erstellen des Termins inklusive ISiKPatient - $book (vorläufig)

TRP -> TR: Buchungsbestätigung

note right of TRP: Termin ist angelegt, Patient verifiziert




@enduml
