id: Subscription
canonical: https://gematik.de/fhir/isik/Subscription
name: Subscription Implementierungsleitfaden
title: Subscription
description: Dieser Implementierungsleitfaden beschreibt eine ISiK-konforme Umsetzung der Subscription im Krankenhaus.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: STU1
license: CC0-1.0
publisher: Test Organization

applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  Patientenzusammenfuehrung.md: 
    title: Patientenzusammenführung
  Fallzusammenfuehrung.md:
    title: Fallzusammenführung
  UseCases.md:
    title: Weitere UseCases
  Akteure.md:
    title: Akteure
  FunktionenInteraktionen.md:
    title: Funktionen und Interaktionen
  Festlegungen.md:
    title: Festlegungen
  artifacts.md:
    title: FHIR-Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Kontext und Use Cases:
  Spezifikation:
    - Patientenzusammenführung: Patientenzusammenfuehrung.html
    - Fallzusammenführung: Fallzusammenfuehrung.html
    - Weitere UseCases: UseCases.html
    - Akteure: Akteure.html
    - Funktionen und Interaktionen: FunktionenInteraktionen.html
  Festlegungen:
    Festlegungen: Festlegungen.html
  FHIR-Artefakte: artifacts.html
    #Artefakte: artifacts.html
    #CapabilityStatements: capabilitystatements.html
    #Profile: profiles.html
    #Terminology: terminology.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true