id: basis
canonical: https://gematik.de/fhir/isik
name: ISiKBasisImplementationGuide
title: ISiK Basis Implementierungsleitfaden
description: Implementation guide for the Basis module based on ISiK specifications.
status: active
version: 6.0.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: active
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.uv.ips: 2.0.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.6.0
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0
  de.gematik.terminology: 1.0.6
  de.gematik.ti: 1.3.1
  de.fhir.medication: 1.0.7
  kbv.all.terminology.allergyintolerance: 1.0.0

pages:
  index.md:
    title: Einführung
  Motivation.md:
    title: Motivation
  ReleaseNotes.md:
    title: Release Notes
  Abbildung-des-Konstrukts-Fall.md:
    title: Abbildung des Konstrukts "Fall"
  Datenuebermittlung-aus-Subsystemen.md:
    title: Datenübermittlung aus Subsystemen
  Erlaeuterung-Akteurs-und-Rollenmodell.md:
    title: Akteurs- und Rollenmodell
  Index_Beispielszenarien.md:
    title: Beispielszenarien
  Szenario-1-DRG-Fall-Kind-mit-Wahlleistung.md:
    title: "Szenario 1: DRG-Fall, Kind mit Wahlleistung"
  Szenario-2-Kreuz-Stern-Diagnose.md:
    title: "Szenario 2: Kreuz-Stern-Diagnose"
  Index_Festlegungen.md:
    title: Festlegungen
    UebergreifendeFestlegungen_Methodik.md:
      title: Methodik
    UebergreifendeFestlegungen_BestaetigungsrelevanteSysteme.md:
      title: Bestätigungsrelevante Systeme
    KompatibilitaetDerGematikSpezifikation_Andere.md:
      title: Kompatibilität der gematik-Spezifikation
    KompatibilitaetDerGematikSpezifikation_IHE.md:
      title: Kompatibilität der gematik-Spezifikation IHE
    KompatibilitaetDerGematikSpezifikation_HL7Europe.md:
      title: Kompatibilität der gematik-Spezifikation HL7 Europe
    UebergreifendeFestlegungen_Must-Support-Flags.md:
      title: Must-Support-Flags
    UebergreifendeFestlegungen_Repraesentationsformate.md:
      title: Repräsentationsformate
    UebergreifendeFestlegungen_Suchparameter.md:
      title: Allgemeine Hinweise zu Suchparametern
    UebergreifendeFestlegungen_Rest.md:
      title: REST-API
    UebergreifendeFestlegungen_Performance.md:
      title: Performance
    Patient-Besuch-Kontext.md:
      title: Herstellung von Patienten- und Besuchskontext
    UebergreifendeFestlegungen_UmgangFehlendeDaten.md:
      title: Umgang mit fehlenden Daten
    UebergreifendeFestlegungen_FHIR_Artefakte.md:
      title: Umgang mit FHIR-Artefakten
  artifacts.md:  
    title: FHIR-Artefakte

menu:
  Einführung: index.html
  Motivation: Motivation.html
  Release Notes: ReleaseNotes.html
  Kontext und Use Cases:
    Abbildung des Konstrukts "Fall": Abbildung-des-Konstrukts-Fall.html
    Datenübermittlung aus Subsystemen: Datenuebermittlung-aus-Subsystemen.html
    Akteurs- und Rollenmodell: Erlaeuterung-Akteurs-und-Rollenmodell.html
    Beispielszenarien: Index_Beispielszenarien.html
  Festlegungen:
    Methodik: UebergreifendeFestlegungen_Methodik.html
    Bestätigungsrelevante Systeme: UebergreifendeFestlegungen_BestaetigungsrelevanteSysteme.html
    Kompatibilität der gematik-Spezifikation Andere: KompatibilitaetDerGematikSpezifikation_Andere.html
    Kompatibilität der gematik-Spezifikation IHE: KompatibilitaetDerGematikSpezifikation_IHE.html
    Kompatibilität der gematik-Spezifikation HL7 Europe: KompatibilitaetDerGematikSpezifikation_HL7Europe.html
    Must-Support-Flags: UebergreifendeFestlegungen_Must-Support-Flags.html
    Repräsentationsformate: UebergreifendeFestlegungen_Repraesentationsformate.html
    Suchparameter: UebergreifendeFestlegungen_Suchparameter.html
    REST-API: UebergreifendeFestlegungen_Rest.html
    Performance: UebergreifendeFestlegungen_Performance.html
    Herstellung von Patienten- und Besuchskontext: Patient-Besuch-Kontext.html
    Umgang mit fehlenden Daten: UebergreifendeFestlegungen_UmgangFehlendeDaten.html
    Umgang mit FHIR-Artefakten: UebergreifendeFestlegungen_FHIR_Artefakte.html
  FHIR-Artefakte: artifacts.html
 

parameters:
  display-warnings: true
  path-expansion-params: ../../input/resources/Parameters-exp-params.json
  special-url:
    - http://example.org/fhir/CodeSystem/TestKatalog
    - http://example.org/fhir/ValueSet/TestValueSet


#und ggfs noch:
#  no-narrative: true
