
Instance: ISiKFormularClient
InstanceOf: CapabilityStatement
Usage: #definition
* name = "ISiKFormularClient"
* title = "ISiK Formular Client (Questionnaire-Renderer)"
* description = ""
* kind = #requirements
* date = "2024-07-06"
* status = #draft
* fhirVersion = #4.0.1
* format[0] = #xml
* format[+] = #json
* rest
  * mode = #client
  * documentation = "The [[Questionnaire]], [[ValueSet]] and [[CodeSystem]] resources are retrieved to allow the system to guide the user through the entry process.  The [[Binary]] and [[DocumentReference]] resources allow the system to find existing clinical documents that can be within the pre-population process.  (Support for retrieval operations on these resources is optional as the relevant CDA or FHIR structures may also be directly generated by the ''Form Filler'' itself.)  Finally, the [[QuestionnaireResponse]] resource is used to record the populated form.<br/>Note: Form Fillers that support the 'populate' operation will need to be capable of consuming and rendering a partially completed QuestionnaireResponse in the same manner as if they had retrieved such a QuestionnaireResponse from a ''Form Response Manager''"
  * security.description = "Implementations must meet the general security requirements documented in the [[security.html|SDC implementation guide]]."
  * resource[0]
    * type = #Questionnaire
    * profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire"
    * interaction[0]
      * insert Expectation (#SHALL)
      * code = #search-type
      * documentation = "Allows discovery of existing questionnaires to be completed"
    * interaction[+]
      * insert Expectation (#SHOULD)
      * code = #read
      * documentation = "Allows retrieval of a specific questionnaire by id.  Allows systems to maintain a 'favorites' list of forms and retrieve them by id."
    * interaction[+]
      * insert Expectation (#MAY)
      * code = #history-instance
      * documentation = "Allows review of changes made to a questionnaire over time.  Of interest to some systems, but probably not most."
    * interaction[+]
      * insert Expectation (#MAY)
      * code = #vread
      * documentation = "Allows retrieval of a historical version of a questionnaire.  Most systems will make use of the current version only."
  * resource[+]
    * type = #ValueSet
    * profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-valueset"
    * interaction[0]
      * insert Expectation (#SHALL)
      * code = #read
      * documentation = "Allows retrieval of a specific value set by id (as referenced in a Questionnaire)"
    * interaction[+]
      * insert Expectation (#SHOULD)
      * code = #vread
      * documentation = "Allows retrieval of a specific version of a value set (as referenced in a Questionnaire)"
    * interaction[+]
      * insert Expectation (#MAY)
      * code = #history-instance
      * documentation = "Allows review of changes to a value set over time.  Of interest to some systems, but probably not most."
  * resource[+]
    * type = #CodeSystem
    * profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-codesystem"
    * interaction[0]
      * insert Expectation (#SHALL)
      * code = #read
      * documentation = "Allows retrieval of a specific code system by id (as referenced by a ValueSet used in a Questionnaire)"
    * interaction[+]
      * insert Expectation (#SHOULD)
      * code = #vread
      * documentation = "Allows retrieval of a specific version of a code system (as referenced by a ValueSet used in a Questionnaire)"
    * interaction[+]
      * insert Expectation (#MAY)
      * code = #history-instance
      * documentation = "Allows review of changes to a code system over time.  Of interest to some systems, but probably not most."
  * resource[+]
    * type = #QuestionnaireResponse
    * profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaireresponse"
    * interaction[0]
      * insert Expectation (#SHALL)
      * code = #search-type
      * documentation = "Allows a user to search for existing completed or partially-completed forms.  Generally used to find partially-completed forms for update."
    * interaction[+]
      * insert Expectation (#SHALL)
      * code = #read
      * documentation = "Allows retrieval of a specific QuestionnaireResponse by id."
    * interaction[+]
      * insert Expectation (#SHALL)
      * code = #create
      * documentation = "Allows recording a completed or partially-completed form"
    * interaction[+]
      * insert Expectation (#SHALL)
      * code = #update
      * documentation = "Allows updating an existing completed or partially-completed form.  (Systems may place rules on who can update forms and under what circumstances.)"
    * interaction[+]
      * insert Expectation (#SHALL)
      * code = #delete
      * documentation = "Allows removal of a completed form from a repository.  Note that the removal may be logical rather than physical.  Some systems may have rules for who can remove a completed form and under what circumstances."
    * interaction[+]
      * insert Expectation (#SHOULD)
      * code = #history-instance
      * documentation = "Allows review of prior versions of an answer set - allows reversion to previously recorded versions"
  * resource[+]
    * type = #DocumentReference
    * interaction
      * insert Expectation (#SHOULD)
      * code = #search-type
      * documentation = "Allows discovery of existing documents that may be included in a form pre-population request"
  * resource[+]
    * type = #Binary
    * interaction[0]
      * insert Expectation (#SHOULD)
      * code = #read
      * documentation = "Allows retrieval of a specific binary (as pointed to by a DocumentReference)"
    * interaction[+]
      * insert Expectation (#MAY)
      * code = #vread
      * documentation = "Allows retrieval of a historical version of a binary.  In general, the most recent version would be appropriate, but some may prefer to use the specific version referenced by a DocumentReference."
  * operation[0]
    * insert Expectation (#SHOULD)
    * name = "expand"
    * definition = "http://hl7.org/fhir/OperationDefinition/ValueSet-expand"
  * operation[+]
    * insert Expectation (#SHOULD)
    * name = "validate code"
    * definition = "http://hl7.org/fhir/OperationDefinition/ValueSet-validate-code"
  * operation[+]
    * insert Expectation (#MAY)
    * name = "populate"
    * definition = "http://hl7.org/fhir/uv/sdc/OperationDefinition/Questionnaire-populate"
  * operation[+]
    * insert Expectation (#MAY)
    * name = "populatehtml"
    * definition = "http://hl7.org/fhir/uv/sdc/OperationDefinition/Questionnaire-populatehtml"
  * operation[+]
    * insert Expectation (#MAY)
    * name = "populatelink"
    * definition = "http://hl7.org/fhir/uv/sdc/OperationDefinition/Questionnaire-populatelink"