id: basis.test.ig
canonical: http://example.org/fhir/test-basis-ig
name: TestImplementationGuide
title: Test Implementation Guide
description: A test implementation guide for validating the local FHIR IG Publisher environment
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: STU1
license: CC0-1.0
publisher: Test Organization

applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Index
  Motivation.md:
    title: Motivation
  ReleaseNotes.md:
    title: Release Notes
  Index_UseCaseAnwendung.md:
    title: Use Cases und Anwendungskontexte
  Abbildung-des-Konstrukts-Fall.md:
    title: Abbildung des Konstrukts "Fall"
  Datenuebermittlung-aus-Subsystemen.md:
    title: Datenübermittlung aus Subsystemen
  Erlaeuterung-Akteurs-und-Rollenmodell.md:
    title: Akteurs- und Rollenmodell
  Index_Beispielszenarien.md:
    title: Beispielszenarien
  Szenario-1-DRG-Fall-Kind-mit-Wahlleistung.md:
    title: "Szenario 1: DRG-Fall, Kind mit Wahlleistung"
  Szenario-2-Kreuz-Stern-Diagnose.md:
    title: "Szenario 2: Kreuz-Stern-Diagnose"
  Index_Festlegungen.md:
    title: Festlegungen
  UebergreifendeFestlegungen_Methodik.md:
    title: Methodik
  UebergreifendeFestlegungen_BestaetigungsrelevanteSysteme.md:
    title: Bestätigungsrelevante Systeme
  KompatibilitaetDerGematikSpezifikation_Andere.md:
    title: Kompatibilität der gematik-Spezifikation
  KompatibilitaetDerGematikSpezifikation_IHE.md:
    title: Kompatibilität der gematik-Spezifikation IHE
  UebergreifendeFestlegungen_Must-Support-Flags.md:
    title: Must-Support-Flags
  UebergreifendeFestlegungen_Repraesentationsformate.md:
    title: Repräsentationsformate
  UebergreifendeFestlegungen_Suchparameter.md:
    title: Suchparameter
  UebergreifendeFestlegungen_Rest.md:
    title: REST-API
  Patient-Besuch-Kontext.md:
    title: Herstellung von Patienten- und Besuchskontext
  UebergreifendeFestlegungen_UmgangFehlendeDaten.md:
    title: Umgang mit fehlenden Daten


menu:
  Index: index.html
  Motivation: Motivation.html
  Release Notes: ReleaseNotes.html
  Kontext und Use Cases:
    Index: Index_UseCaseAnwendung.html
    Abbildung des Konstrukts "Fall": Abbildung-des-Konstrukts-Fall.html
    Datenübermittlung aus Subsystemen: Datenuebermittlung-aus-Subsystemen.html
    Akteurs- und Rollenmodell: Erlaeuterung-Akteurs-und-Rollenmodell.html
    Beispielszenarien: Index_Beispielszenarien.html
    "Szenario 1": Szenario-1-DRG-Fall-Kind-mit-Wahlleistung.html
    "Szenario 2": Szenario-2-Kreuz-Stern-Diagnose.html
  Festlegungen:
    Index: Index_Festlegungen.html
    Methodik: UebergreifendeFestlegungen_Methodik.html
    Bestätigungsrelevante Systeme: UebergreifendeFestlegungen_BestaetigungsrelevanteSysteme.html
    Kompatibilität der gematik-Spezifikation Andere: KompatibilitaetDerGematikSpezifikation_Andere.html
    Kompatibilität der gematik-Spezifikation IHE: KompatibilitaetDerGematikSpezifikation_IHE.html
    Must-Support-Flags: UebergreifendeFestlegungen_Must-Support-Flags.html
    Repräsentationsformate: UebergreifendeFestlegungen_Repraesentationsformate.html
    Suchparameter: UebergreifendeFestlegungen_Suchparameter.html
    REST-API: UebergreifendeFestlegungen_Rest.html
    Herstellung von Patienten- und Besuchskontext: Patient-Besuch-Kontext.html
    Umgang mit fehlenden Daten: UebergreifendeFestlegungen_UmgangFehlendeDaten.html
  FHIR-Artefakte:
    Artefakte: artifacts.html
    CapabilityStatements: capabilitystatements.html
    Profile: profiles.html
    Terminology: terminology.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true