id: medikation
canonical: https://gematik.de/fhir/isik/
name: MedikationImplementationGuide
title: ISiK Medikation
description: Dieser Implementierungsleitfaden spezifiziert eine ISiK-konforme Umsetzung der Medikation im Krankenhaus.
status: active
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de


applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Einführung
  AkteureUndInteraktionen.md:
    title: Akteure und Interaktionen
  BestaetigungsrelevanteSysteme.md:
    title: Bestätigungsrelevante Systeme
  Informationsmodell.md:
    title: Informationsmodell
  Kompatibilitaet.md:
    title: Kompatibilität
  ReleaseNotes.md:
    title: Release Notes
  RestApi.md:
    title: REST-API
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen
  UebersichtAnwendungsfaelle.md:
    title: Übersicht Anwendungsfälle
  artifacts.md:
    title: Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases:
    Übersicht Anwendungsfälle (Use Cases): UebersichtAnwendungsfaelle.html
    Informationsmodell: Informationsmodell.html
  Übergreifende Festlegungen:
    Übergreifende Festlegungen: UebergreifendeFestlegungen.html
    Bestätigungsrelevante Systeme: BestaetigungsrelevanteSysteme.html
    Kompatibilität: Kompatibilitaet.html
    REST-API: RestApi.html
    Akteure und Interaktionen: AkteureUndInteraktionen.html
  FHIR-Artefakte: artifacts.html
 



parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true