id: medikation
canonical: https://gematik.de/fhir/isik
name: MedikationImplementationGuide
title: ISiK Medikation Implementierungsleitfaden
description: Dieser Implementierungsleitfaden spezifiziert eine ISiK-konforme Umsetzung der Medikation im Krankenhaus.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ballot
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de


applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.uv.ips: 2.0.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.6.0-ballot2
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.4
  de.gematik.ti: 1.1.1
  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  UebersichtAnwendungsfaelle.md:
    title: Übersicht Anwendungsfälle
  AnwendungsfallClosedLoopMedikationsprozess.md:
    title: Anwendungsfall - Closed Loop Medikationsprozess  
  Bedarfsmedikation.md:
    title: Bedarfsmedikation
  Infusionen.md:
    title: Infusionen
  Informationsmodell.md:
    title: Informationsmodell
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen
  Kompatibilitaet.md:
    title: Kompatibilität
  RestApi.md:
    title: REST-API
  AkteureUndInteraktionen.md:
    title: Akteure und Interaktionen
  artifacts.md:
    title: Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases:
    Übersicht Anwendungsfälle (Use Cases): UebersichtAnwendungsfaelle.html
    Anwendungsfall - Closed Loop Medikationsprozess: AnwendungsfallClosedLoopMedikationsprozess.html
    Bedarfsmedikation: Bedarfsmedikation.html
    Infusionen: Infusionen.html
    Informationsmodell: Informationsmodell.html
  Übergreifende Festlegungen:
    Übergreifende Festlegungen: UebergreifendeFestlegungen.html
    Kompatibilität: Kompatibilitaet.html
    REST-API: RestApi.html
    Akteure und Interaktionen: AkteureUndInteraktionen.html
  FHIR-Artefakte: artifacts.html
 
parameters:
  display-warnings: true
  path-expansion-params: ../../input/resources/Parameters-exp-params.json
  special-url:
    - http://example.org/fhir/CodeSystem/TestKatalog
    - http://example.org/fhir/ValueSet/TestValueSet

#und ggfs noch:
#  no-narrative: true
