id: example.test.ig
canonical: http://example.org/fhir/test-subscription-ig
name: TestImplementationGuide
title: Test Implementation Guide
description: A test implementation guide for validating the local FHIR IG Publisher environment
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: STU1
license: CC0-1.0
publisher: Test Organization

applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Home
  releasenotes.md:
    title: "Release Notes"
  festlegungen.md:
    title: "Festlegungen"
  Patientenzusammenfuehrung.md:
    title: "Patientenzusammenführung"
  Fallzusammenfuehrung.md:
    title: "Fallzusammenführung"
  UseCases.md:
    title: "Weitere Use Cases"
  Akteure.md:
    title: "Akteure"
  FunktionenInteraktionen.md:
    title: "Funktionen und Interaktionen"
  artifacts.md:
    title: "FHIR-Artefakte"
  profiles.md:
    title: "Profile"
  terminology.md:
    title: "Terminology"
  capabilitystatements.md:
    title: "Capability Statements"

menu:
  Home: index.html
  Release Notes: releasenotes.html
  Spezifikation:
    Patientenzusammenfuehrung: Patientenzusammenfuehrung.html
    Fallzusammenfuehrung: Fallzusammenfuehrung.html
    Weitere Use Cases: UseCases.html
    Akteure: Akteure.html
    Funktionen und Interaktionen: FunktionenInteraktionen.html
  Festlegungen: festlegungen.html
  FHIR-Artefakte:
    Artefakte: artifacts.html
    CapabilityStatements: capabilitystatements.html
    Profile: profiles.html
    Terminology: terminology.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true