canonical: https://gematik.de/fhir/isik
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.5.0
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.subscriptions-backport: 1.1.0
