canonical: https://gematik.de/fhir/ISiK
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: de.gematik.isik-basismodul
name: Implementierungsleitfaden ISiK-Basismodul Stufe1
status: active
version: 1.0.8
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.4.0
  hl7.fhir.r4.core: 4.0.1
