canonical: https://gematik.de/fhir/ISiK
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul Stufe1 1.0.6
name: Implementierungsleitfaden ISiK-Basismodul Stufe1 1.0.6
status: active
version: "1.0.6"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.2.0
  hl7.fhir.r4.core: 4.0.1
