id: vitalparameter
canonical: https://gematik.de/fhir/isik
name: ISiKVitalparameterImplementationGuide
title: ISiK Vitalparameter Implementierungsleitfaden
description: Implementation guide for the Vitalparameter module based on ISiK specifications.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ballot
license: Apache-2.0
language: de
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.uv.ips: 2.0.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.6.0-ballot2
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.4
  de.gematik.ti: 1.1.1

  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  AMTS.md:
    title: Konzept Arzneimitteltherapiesicherheit - AMTS
  Intensivversorgung.md:
    title: Überleitung Intensivversorgung im Krankenhaus
  Festlegungen_Uebergreifend.md:
    title: Übergreifende Festlegungen
  InteraktionenAkteure.md:
    title: Interaktionen und Akteure
  Kompatibilitaet.md:
    title: Kompatibilität
  Signaldaten.md:
    title: Signaldaten
  RestApi.md:
    title: REST-API
  artifacts_isik.md:
    title: FHIR-Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Übergreifende UseCases:
    Konzept Arzneimitteltherapiesicherheit - AMTS: AMTS.html
    Überleitung Intensivversorgung im Krankenhaus: Intensivversorgung.html
  Festlegungen:
    Übergreifende Festlegungen: Festlegungen_Uebergreifend.html
    Interaktionen und Akteure: InteraktionenAkteure.html
    Kompatibilität: Kompatibilitaet.html
    Signaldaten: Signaldaten.html
    REST-API: RestApi.html
  FHIR-Artefakte: artifacts_isik.html
 
parameters:
  display-warnings: true
  path-expansion-params: ../../input/resources/Parameters-exp-params.json
  special-url:
    - http://example.org/fhir/CodeSystem/TestKatalog
    - http://example.org/fhir/ValueSet/TestValueSet

#und ggfs noch:
#  no-narrative: true