@startuml amts_resourcediagram

' verhindere Probleme mit gewinkelten Krähenfüßen
'skinparam linetype ortho
 
' package Dummy{
' Entität01 }|..|| Entität02
' Entität03 }o..o| Entität04
' Entität05 ||--o{ Entität06
' Entität07 |o--|| Entität08
' }
 
 ' TODO:
 ' Vervollständigen im Sinne von: https://github.com/gematik/spec-ISiK-Medikation/blob/rc/main-stufe-4/Material/docs/Medikation%20Abgleich%20bestehende%20Spezifikationen.xlsx

namespace ISiK_VitalparameterUndKoerpermasze {
   class ModulVitalparameterUndKoerpermasze <<(M,#FFDC36)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-vitalparameter-v4 ISiK VitalparameterUndKoerpermasze Stufe 4]]
   }
   class ISiKKoerpergewicht <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-vitalparameter-und-koerpermasze-v4/isikkoerpergewicht ISiK Körpergewicht]]
      ---
      code
      |_ coding
         |_ loinc : code **29463-7**
         |_ snomed : **ISiKKoerpergewichtSCTVS**
      . . .
   }
   class ISiKKoerpergroesse <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-vitalparameter-v4/isikkoerpergroesse ISiK Koerpergroesse]]
      ---
      code
      |_ coding
         |_ loinc : code **8302-2**
         |_ snomed : **ISiKKoerpergroesseSCTVS**
      . . .
   }
}

namespace ISiK_Basis {
   class Basismodul_Stufe_4 <<(M,#FFDC36)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/~introduction ISiK Basis Stufe 4]]
   }
   class ISiKPatient <Patient><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikpatient ISiK Patient]]
   }
   class ISiKKontaktGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikkontaktgesundheitseinrichtung ISiK Kontakt Gesundheitseinrichtung]]
   }  
   class ISiKKDiagnose <Condition><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikdiagnose ISiK Diagnose]]
   }
   
   class ISiKAllergieUnvertraeglichkeit <AllergyIntolerance><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-basis-v4/markdown-Datenobjekte-Datenobjekte_AllergieUnvertraeglichkeit hier]] oder auf
      Simplifier [[https://simplifier.net/isik-basis-v4/isikallergieunvertraeglichkeit ISiK Allergie Unvertraeglichkeit]]
      ---
      type : **AllergyIntoleranceType**
      category : **AllergyIntoleranceCategory**
      criticality : **AllergyIntoleranceCriticality**
      code
      |_ coding
         |_ snomed-ct
         |_ ask 
         |_ atc     
      |_ text
      patient : Reference (**Patient**)
      encounter : Reference (**Encounter**)
      onset[x]
      |_ onsetDateTime
      |_ onsetAge
      |_ onsetString
      recordedDate : dateTime
      recorder : Reference (**Practitioner** | PractitionerRole | \n**Patient** | RelatedPerson)
      |_ reference
      |_ display
      asserter	: Reference (**Patient** | **RelatedPerson** | \n**Practitioner** | PractitionerRole)
      |_ reference
      |_ display      
      note : Annotation
      |_ author[x]
      reaction
      |_ manifestation
         |_ coding
         |_ text      
      |_ severity	
      |_ exposureRoute
   }

   namespace Observations {

      class ISiKLebensZustand <Observation><<(P,#8DA5C4)>>{
         status : **ObservationStatus**
         code
         subject : Reference ( **Patient** | \nGroup | Device | Location)
         |_ reference
         effective[x]
         value[x]
      }

      class ISiKAlkoholAbusus <Observation><<(P,#8DA5C4)>>{
         category : secondary-finding **social-history**
         code : snomed sct **15167005**
         value[x]
         |_ valueBoolean
      }

      class ISiKRaucherStatus <Observation><<(P,#8DA5C4)>>{
         category : secondary-finding **social-history**
         code : snomed sct **77176002**
         value[x]
         |_ valueBoolean
      }

      class ISiKSchwangerschaftErwarteterEntbindungstermin <Observation><<(P,#8DA5C4)>>{
         code : **SchwangerschaftEtMethodeVS**
         value[x]
         |_ valueDateTime
      }

      class ISiKSchwangerschaftsstatus <Observation><<(P,#8DA5C4)>>{
         code : loinc **82810-3**
         value[x]
         |_ valueCodeableConcept : **SchwangerschaftsstatusVS**
         hasMember : Reference \n\t( **ISiKSchwangerschaftErwarteterEntbindungstermin** )
         |_ reference
      }

      class ISiKStillstatus <Observation><<(P,#8DA5C4)>>{
         code : snomed sct **1260078007**
         value[x]
         |_ valueBoolean
      }
   }

      class SchwangerschaftEtMethodeVS <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-basis-v4/schwangerschaftetmethodevs Schwangerschaft Estimated Methode]]
         Includes following codes from the code System
         [[http://loinc.org LOINC]]
         --
         **11778-8** displays-as **Delivery date Estimated**
         **11779-6** displays-as **Delivery date Estimated** \n** from last menstrual period**
         **11780-4** displays-as **Delivery date Estimated** \n** from ovulation date**
      }

      class SchwangerschaftsstatusVS <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-basis-v4/schwangerschaftsstatusvs Schwangerschaft Status]]
         Includes following codes from the code System
         [[http://loinc.org LOINC]]
         --
         **LA15173-0** displays-as **Pregnant**
         **LA26683-5** displays-as **Not pregnant**
         **LA4489-6** displays-as **Unknown**
      }

}

namespace ISiK_Medikation {

   class ISiKAMTSBewertung <RiskAssessment><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-medikation-v4/ImplementationGuide-markdown-Datenobjekte-Profile_AMTSBewertung hier]] oder auf
      Simplifier [[https://simplifier.net/isik-medikation-v4/isikamtsbewertung ISiK AMTS Bewertung]]
      ---
      id
      status
      code
      |_ coding
      |_ text
      subject : Reference( **Patient** )
      |_ reference
      encounter : Reference( **Encounter** )
      |_ reference
      occurrence[x]
      |_ occurrenceDateTime
      |_ occurrencePeriod
      condition : Reference( **Condition** )
      |_ reference
      reasonCode
      |_ coding
      |_ text
      reasonReference : Reference( **Condition** | **Observation** | \nDiagnosticReport | **DocumentReference** )
      |_ reference
      basis : Reference( **Resource** )
      |_ reference
      prediction
      |_ outcome
         |_ coding        
         |_ text
      . . .
   }
   
   class ISiKMedikament <Medication><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-medikation-v4/ImplementationGuide-markdown-Datenobjekte-Profile_Medikament hier]] oder auf 
      Simplifier [[https://simplifier.net/isik-medikation-v4/isikmedikament ISiK Medikament]]
      ---
   }
   'ISiKMedikation::itemReference --> ISiKMedikation

   class ISiKMedikationsInformation <MedicationStatement><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-medikation-v4/ImplementationGuide-markdown-Datenobjekte-Profile_MedikationsInformation hier]] oder auf 
      Simplifier [[https://simplifier.net/isik-medikation-v4/isikmedikationsinformation ISiK Medikationsinformation]]
      ---
      id
      ...
      ...
      AcceptedRisk : **Extension**
      |_ text
      |_ Bewertung : **ISiKAMTSBewertung**
   }

   class ISiKMedikationsVerabreichung <MedicationAdministration><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-medikation-v4/ImplementationGuide-markdown-Datenobjekte-Profile_MedikationsVerabreichung hier]] oder auf 
      Simplifier [[https://simplifier.net/isik-medikation-v4/isikmedikationsverabreichung ISiK Medikationsverabreichung]]
      ---
      id
      ...
      ...
      AcceptedRisk : **Extension**
      |_ text
      |_ Bewertung : **ISiKAMTSBewertung**
   }

   class ISiKMedikationsVerordnung <MedicationRequest><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-medikation-v4/ImplementationGuide-markdown-Datenobjekte-Profile_MedikationsVerordnung hier]] oder auf
      Simplifier [[https://simplifier.net/isik-medikation-v4/isikmedikationsverordnung ISiK Medikationsverordnung]]
      ---
      id
      ...
      ...
      AcceptedRisk : **Extension**
      |_ text
      |_ Bewertung : **ISiKAMTSBewertung**
   }
}

namespace ISiK_Labor {
    class Labor_Stufe_4 <<(M,#FFDC36)>>{
      Dokumentation auf Simplifier Projekt TBD
      [[https://simplifier.net/isik-labor-v4/~introduction ISiK Labor (Support Modul)]]
   }
 
 class ISiKLaboruntersuchung <Observation><<(P,#8DA5C4)>>{
      Dokumentation [[https://simplifier.net/guide/isik-labor-v4/ImplementationGuide-markdown-Datenobjekte-Profile_Laboruntersuchung hier]] oder auf
      Simplifier [[https://simplifier.net/isik-labor-v4/isiklaboruntersuchung ISiK Laboruntersuchung]]
      ---
       id
      status : **ObservationStatus*
      category : **ObservationCategoryCodes**
      code : **LOINCCodes**
      |_ coding
      |_ text
      subject : Reference ( **Patient** | Group | Device | Location)
      encounter : Reference ( **Encounter** )
      effective[x]
      |_ effectiveDateTime
      issued
      value[x]
      |_ valueQuantity
      specimen : Reference (Specimen)
      |_ reference
      |_ identifier
      device : Reference ( Device | DeviceMetric )
      referenceRange
      |_ low
      |_ high 
      |_ type : **ObservationReferenceRangeMeaningCodes**
         |_ coding
         |_ text
      |_ appliesTo
         |_ coding
         |_ text
   }
   'ISiKMedikation::itemReference --> ISiKMedikation

   class ISiKLaboruntersuchungCRP <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesCRP**
         |_ snomed : code **55235003**
      value[x]
      |_ valueQuantity : **ObservationUnitsCRP**
      ...
      ...
   }

   class ISiKLaboruntersuchungGFR <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesGFR**
         |_ snomed : code **80274001**
      value[x]
      |_ valueQuantity : **ObservationUnitsGFR**
      ...
      ...
   }

   class ISiKLaboruntersuchungHb <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesHb**
         |_ snomed : code **416125006**
      value[x]
      |_ valueQuantity : **ObservationUnitsHb**
      ...
      ...
   }

   class ISiKLaboruntersuchungPCT <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesPCT**
         |_ snomed : code **418752001**
      value[x]
      |_ valueQuantity : **ObservationUnitsPCT**
      ...
      ...
   }

   class ISiKLaboruntersuchungSerumkreatinin <Observation><<(P,#8DA5C4)>>{
     |_ coding
         |_ loinc : **ObservationCodesSerumkreatinin**
         |_ snomed : code **70901006**
      value[x]
      |_ valueQuantity : **ObservationUnitsSerumkreatinin**
      ...
      ...
   }

   class ISiKLaboruntersuchungThrombozyten <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesThrombozyten**
         |_ snomed : code **365632008**
      value[x]
      |_ valueQuantity : **ObservationUnitsThrombozyten**
      ...
      ...
   }
   class ISiKLaboruntersuchungTroponin <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesTroponin**
         |_ snomed : code **105000003**
      value[x]
      |_ valueQuantity : **ObservationUnitsTroponin**
      ...
      ...
   }

   class ISiKLaboruntersuchungTSH <Observation><<(P,#8DA5C4)>>{
      |_ coding
         |_ loinc : **ObservationCodesTSH**
         |_ snomed : code **61167004**
      value[x]
      |_ valueQuantity : **ObservationUnitsTSH**
      ...
      ...
   }

   namespace Observations_Codes {
      class ObservationCodesCRP <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodescrp Observation Codes CRP]]
         Includes codes from the code System
         [[http://loinc.org LOINC]]
         --
         **1988-5**
         **76485-2**
         ...
         ...
      }

      class ObservationCodesGFR <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodesgfr Observation Codes GFR]]
         Includes various codes from the code System
         [[http://loinc.org LOINC]]
         --
         **98980-6**
         **98979-8**
         ...
         ...
      }

      class ObservationCodesHb <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodeshb Observation Codes Hb]]
         Includes codes from the code System
         [[http://loinc.org LOINC]]
         --
         **718-7**
         **59260-0**
         ...
         ...
      }

      class ObservationCodesPCT <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodespct Observation Codes PCT]]
         Includes codes from the code System
         [[http://loinc.org LOINC]]
         --
         **33959-8**
         ...
         ...
      }

      class ObservationCodesSerumkreatinin <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodesserumkreatinin Observation Codes Serumkreatinin]]
         Includes various codes from the code System
         [[http://loinc.org LOINC]]
         --
         **2160-0**
         **14682-9**
         ...
         ...
      }

      class ObservationCodesThrombozyten <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodesthrombozyten Observation Codes Thrombozyten]]
         Includes various codes from the code System
         [[http://loinc.org LOINC]]
         --
         **26515-7**
         ...
         ...
      }

      class ObservationCodesTroponin <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodestroponin Observation Codes Troponin]]
         Includes various codes from the code System
         [[http://loinc.org LOINC]]
         --
         **42757-5**
         ...
         ...
      }

      class ObservationCodesTSH <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationcodestsh Observation Codes TSH]]
         Includes various codes from the code System
         [[http://loinc.org LOINC]]
         --
         **3015-5**
         ...
         ...
      }

   }
   namespace Observations_Units {
      class ObservationUnitsCRP <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitscrp Observation Units CRP]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **mg/L** displays-as **milligram per liter**
         **nmol/L** displays-as **nanomol per liter**
      }

      class ObservationUnitsGFR <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitsgfr Observation Units GFR]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **mL/min/{1.73_m2}** displays-as **milliliter pro** \n**Minute pro Körperoberfläche von 1,73 m2**
      }

      class ObservationUnitsHb <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitshb Observation Units Hb]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **g/dL** displays-as **gram per deciliter**
         **mmol/L** displays-as **millimol per liter**
      }

      class ObservationUnitsPCT <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitspct Observation Units PCT]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **ng/mL** displays-as **nanogram per milliliter**
      }

      class ObservationUnitsSerumkreatinin <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitsserumkreatinin Observation Units Serumkreatinin]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **mg/dL** displays-as **milligram per deciliter**
         **umol/L** displays-as **micromol per liter**
      }

      class ObservationUnitsThrombozyten <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitsthrombozyten Observation Units Thrombozyten]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **10*3/uL** displays-as **10^3 per microliter**
      }

      class ObservationUnitsTroponin <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitstroponin Observation Units Troponin]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **ng/mL** displays-as **nanogram per milliliter**
         **ug/L** displays-as **microgram per liter**
      }

      class ObservationUnitsTSH <ValueSet><<(V,#8DA5C4)>>{
         Dokumentation auf Simplifier 
         [[https://simplifier.net/isik-labor-v4/observationunitstsh Observation Units TSH]]
         Includes codes from the code System
         [[http://unitsofmeasure.org UCUM]]
         --
         **m[IU]/L** displays-as **milli IU per liter**
         **u[IU]/mL** displays-as **micro IU per milliliter**
      }
   }

}

namespace HL7_FHIR_R4_Core {
   class Foundation_Modul <<(M,#FFAAAA)>>{
      Dokumentation auf HL7 Org
      [[https://hl7.org/fhir/R4/ HL7 FHIR R4 Core Foundation]]
   }

   class LOINCCodes <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/observation-codes Observation Codes]]
      Includes all codes from the underlying code system [[https://loinc.org/ LOINC]]
   }

   class AllergyIntoleranceCriticality <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-allergy-intolerance-criticality.html Allergy Intolerance Criticality]]
      Das entsprechende Standard-ValueSet beeinhatet das komplette \nCode System des zugehörigen [[https://hl7.org/fhir/R4/codesystem-allergy-intolerance-criticality.html Code System of Criticality]]
   }
   class AllergyIntoleranceVerificationStatus <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://www.hl7.org/fhir/R4/valueset-allergyintolerance-verification.html Allergy Intolerance Verification Status]]
      Das entsprechende Standard-ValueSet beeinhatet das komplette \nCode System des zugehörigen [[https://www.hl7.org/fhir/R4/codesystem-allergyintolerance-verification.html Code System of Verification Status]]
   }
   class AllergyIntoleranceClinicalStatus <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://www.hl7.org/fhir/R4/valueset-allergyintolerance-clinical.html Allergy Intolerance Clinical Status]]
      Das entsprechende Standard-ValueSet beeinhatet das komplette \nCode System des zugehörigen [[https://www.hl7.org/fhir/R4/codesystem-allergyintolerance-clinical.html Code System of Clinical Status]]
   }
   class ReactionEventSeverity <ValueSet><<(V,#8DA5C4)>> {
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-reaction-event-severity.html Reaction Eventu Severity]]
      Das entsprechende Standard-ValueSet beeinhatet das komplette \nCode System des zugehörigen [[https://hl7.org/fhir/R4/codesystem-reaction-event-severity.html Code System of Severity]]
   }
   class ObservationCategory <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-observation-category.html Observation Category]]
      Das entsprechende Standard-ValueSet beeinhatet das komplette \nCode System des zugehörigen [[https://hl7.org/fhir/R4/codesystem-observation-category.html Code System of Observation Category]]
   }

   class ObservationStatus <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-observation-status Observation Status]]
      Includes all codes from the underlying code system 
      [[https://hl7.org/fhir/R4/codesystem-observation-status.html Code System of Observation Status]]
   }

   class ObservationReferenceRangeMeaningCodes <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/referencerange-meaning Observation Reference Meaning Codes]]
      Includes all codes from the underlying code system 
      [[http://terminology.hl7.org/CodeSystem/referencerange-meaning Code System of Observation Reference Meaning Codes]]
   }

   class ObservationMethods <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/observation-methods Observation Methods]]
      Includes codes from the underlying code system 
      [[http://snomed.info/sct SNOMED CT]] where the \nconcept is Technique, Action or Patient evaluation procedure.
      --
      codes : **$CS-SCT** is-a **[[http://snomed.info/id/72394005 272394005]]**
      codes : **$CS-SCT** is-a **[[http://snomed.info/id/129264002 129264002]]**
      codes : **$CS-SCT** is-a **[[http://snomed.info/id/386053000 386053000]]**
   }

   class ObservationInterpretationCodes <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/R4/ValueSet/observation-interpretation Observation Interpretation]]
      Includes all codes from the underlying code system
      [[http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation Code System of Observation Interpretation]]
   }
}

@enduml