@startuml

participant "Client System" as ClientSystem
participant "Server System" as ServerSystem

activate ClientSystem
activate ServerSystem
ClientSystem -> ServerSystem: subscribe to SubscriptionTopic: http://hl7.org/SubscriptionTopic/patient-merge

ServerSystem -> ClientSystem: confirm subscription


ServerSystem -> ServerSystem: $patient-merge with source and target patient
ServerSystem -> ClientSystem: send notification Bundle

@enduml