@startuml dummy
' package Dummy{
' entity Entität01 {
'    optionales Attribut
'    **optionales fettes Attribut**
'    * **vorgeschriebens fettes Attribut**
' }
' 
' entity Entität01 {
'    optionales Attribut : text
'    **optionales fettes Attribut** nummer <<auto>>
'    * **vorgeschriebens fettes Attribut**
' }
' Entität01 }|..|| Entität02
' Entität03 }o..o| Entität04
' Entität05 ||--o{ Entität06
' Entität07 |o--|| Entität08
' }
@enduml


@startuml infomodel_condobs
'verhindere Probleme mit gewinkelten Krähenfüßen
'skinparam linetype ortho

'ISiK_Medikation.ISiKMedikationsListe::subject --> ISiK_Basis.ISiKPatient
'ISiK_Medikation.ISiKMedikationTransaction --> R4_Core.Bundle
'ISiK_Medikation.ISiKMedikationTransactionResponse --|> R4_Core.Bundle

   'ISiKMedikation::itemReference --> ISiKMedikation

'AMTS related
'together {
class ISiKAllergieUnvertraeglichkeit <AllergyIntolerance><<(P,#8DA5C4)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-basis-v4/isikallergieunvertraeglichkeit ISiK AllergieUnvertraeglichkeit]]
   ---
   clinicalStatus : **AllergyIntoleranceClinicalStatusCodes**
   |_ coding
   verificationStatus : **AllergyIntoleranceVerificationStatusCodes**
   |_ coding
   type : **AllergyIntoleranceType**
   category : **AllergyIntoleranceCategory**
   criticality : **AllergyIntoleranceCriticality**
   code
   |_ coding
   . . .
}

class ISiKLebensZustand <Observation><<(P,#8DA5C4)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-basis-v4/isiklebenszustand ISiK LebensZustand]]
   ---
   status : **ObservationStatus**
   code
   subject : Reference ( **Patient** | \nGroup | Device | Location)
   . . .
}

 
   class ISiKAlkoholAbusus <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikalkoholabusus ISiK Alkohol Abusus]]
      ---
      code : snomed sct **15167005**
      . . .
   }
   class ISiKRaucherStatus <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikraucherstatus ISiK Raucherstatus]]
      ---
      code : snomed sct **77176002**
      . . .
   }
'Oservation Childs    
together  {
   class ISiKSchwangerschaftErwarteterEntbindungstermin <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikschwangerschafterwarteterentbindungstermin ISiK Schwangerschaft - Erwarteter Entbindungstermin]]
      ---
      code : **SchwangerschaftEtMethodeVS**
      . . .
   }
   class ISiKSchwangerschaftsstatus <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikschwangerschaftsstatus ISiK Schwangerschaftsstatus]]
      ---
      code : loinc **82810-3**
      . . .
   }
   
   class SchwangerschaftsstatusVS <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/schwangerschaftsstatusvs Schwangerschaft Status]] from [[http://loinc.org LOINC]]
   }

   class ISiKStillstatus <Observation><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikstillstatus ISiK Stillstatus]]
      ---
      code : snomed sct **1260078007**
      . . .
   }
}

   
' Weiteres Basis
together {
   class ISiKPatient <Patient><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikpatient ISiK Patient]]
   }
   
   class ISiKPersonImGesundheitsberuf <Practitioner><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikpersonimgesundheitsberuf ISiK Person im Gesundheitsberuf]]
   }
   class ISiKKontaktGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikkontaktgesundheitseinrichtung ISiK Kontakt Gesundheitseinrichtung]]
   } 
   
   class ISiKAngehoeriger <RelatedPerson><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikangehoeriger ISiK Angehoeriger]]
      ---
      patient : Reference ( **Patient**)
      name : HumanName
      address : Address
      |_ Strassenanschrift	: **Adresse**
      |_ Postfach	: **Adresse**
      . . .
   }
      
}

'Valuesets Observations

   class LOINCCodes <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/observation-codes Observation Codes]] from [[https://loinc.org/ LOINC]]
   }

   class SchwangerschaftEtMethodeVS <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/schwangerschaftetmethodevs Schwangerschaft Estimated Methode]] from [[http://loinc.org LOINC]]
   }


together {
   class AllergyIntoleranceCriticality <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-allergy-intolerance-criticality.html Allergy Intolerance Criticality]] from [[https://hl7.org/fhir/R4/codesystem-allergy-intolerance-criticality.html HL7]]
   }
   class AllergyIntoleranceVerificationStatus <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://www.hl7.org/fhir/R4/valueset-allergyintolerance-verification.html Allergy Intolerance Verification Status]] from [[https://www.hl7.org/fhir/R4/codesystem-allergyintolerance-verification.html HL7]]
   }
   class AllergyIntoleranceClinicalStatus <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://www.hl7.org/fhir/R4/valueset-allergyintolerance-clinical.html Allergy Intolerance Clinical Status]] from [[https://www.hl7.org/fhir/R4/codesystem-allergyintolerance-clinical.html HL7]]
   }
   class AllergyIntoleranceType <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/allergy-intolerance-type Allergy Intolerance Type]] from [[http://hl7.org/fhir/allergy-intolerance-type Code System of Allergy Intolerance]]
   }
   class AllergyIntoleranceCode <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[http://hl7.org/fhir/ValueSet/allergyintolerance-code Substance/Product, Condition, NegationCodes]] from [[http://snomed.info/sct SNOMED CT]]
   }
   class ReactionEventSeverity <ValueSet><<(V,#8DA5C4)>> {
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-reaction-event-severity.html Reaction Eventu Severity]] from [[https://hl7.org/fhir/R4/codesystem-reaction-event-severity.html HL7]]
   }
}


'Relations regarding basis AMTS

'diamonds
'together {
<> MultiRef_PracPatRel
MultiRef_PracPatRel -- ISiKPersonImGesundheitsberuf
MultiRef_PracPatRel -- ISiKPatient
MultiRef_PracPatRel -- ISiKAngehoeriger
<> MultiRef_AllergyDetails
MultiRef_AllergyDetails -up- AllergyIntoleranceCriticality
MultiRef_AllergyDetails -up- AllergyIntoleranceVerificationStatus
MultiRef_AllergyDetails -up- AllergyIntoleranceClinicalStatus
MultiRef_AllergyDetails -up- ReactionEventSeverity
MultiRef_AllergyDetails -up- AllergyIntoleranceType
MultiRef_AllergyDetails -up-> "  1..1  " AllergyIntoleranceCode
'}

'AMTS
ISiKAllergieUnvertraeglichkeit::patient --> "  1..1  " ISiKPatient
ISiKAllergieUnvertraeglichkeit::encounter --> "  0..1  " ISiKKontaktGesundheitseinrichtung
ISiKAllergieUnvertraeglichkeit::recorder --> "  0..1  " MultiRef_PracPatRel
ISiKAllergieUnvertraeglichkeit::recorder .up.  MultiRef_AllergyDetails

'Specific Observations inherit from generic obseration
ISiKLebensZustand <|-- ISiKAlkoholAbusus
ISiKLebensZustand <|-- ISiKRaucherStatus
ISiKLebensZustand <|-- ISiKSchwangerschaftsstatus
ISiKLebensZustand <|-- ISiKSchwangerschaftErwarteterEntbindungstermin
ISiKLebensZustand <|-- ISiKStillstatus

ISiKSchwangerschaftsstatus::hasMember -down-> "  0..1  " ISiKSchwangerschaftErwarteterEntbindungstermin
ISiKSchwangerschaftsstatus::value ..> "  0..1  " SchwangerschaftsstatusVS
ISiKSchwangerschaftErwarteterEntbindungstermin::code ..> "  1..1  " SchwangerschaftEtMethodeVS 

' namespace dummy {
'    class Foo {
'    + field1
'    + field2
'    }
'    class Bar {
'    + field3
'    + field4
'    }
'    Foo::field1 --> Bar::field3 : foo
'    Foo::field2 --> Bar::field4 : bar
' }
@enduml