@startuml 

namespace ISiK_Basis {

    namespace ISiK_Basis_NEU_Standort_Organisation {

    class ISiKStandort <Location><<(P,#1dde23)>>
    ' https://build.fhir.org/location.html

    class ISiKStandortRaum <Location><<(P,#1dde23)>>

    class ISiKStandortBettenstellplatz <Location><<(P,#1dde23)>>

    class ISiKOrganisationFachbteilung <Schedule><<(P,#1dde23)>>

    ISiKStandort	<|-- ISiKStandortRaum
    ISiKStandort	<|-- ISiKStandortBettenstellplatz
    ISiKStandort o-- ISiKStandort : .partof 0..1

    ' https://build.fhir.org/organization.html
    class ISiKOrganisationFachbteilung <Schedule><<(P,#1dde23)>>
    ISiKOrganisationFachbteilung o-- ISiKStandort : managingOrganization 0..1

    }

    class ISIK_KontaktmitGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>
    
    ISiK_Basis.ISiK_Basis_NEU_Standort_Organisation.ISiKOrganisationFachbteilung o-- ISIK_KontaktmitGesundheitseinrichtung : .serviceProvider

}

note top of ISiK_Basis: Nur für Standort und Organisation wesentliche Profile


namespace ISiK_Terminplanung {
    class ISiKKalender <Schedule><<(P,#8DA5C4)>>
    class ISiKMedizinischeBehandlungseinheit <HealthcareService><<(P,#8DA5C4)>>
    class ISiKNachricht <Communication><<(P,#8DA5C4)>>
}

ISiK_Basis.ISiK_Basis_NEU_Standort_Organisation.ISiKStandort o-- ISiK_Terminplanung.ISiKKalender : .actor 1..*
ISiK_Basis.ISiK_Basis_NEU_Standort_Organisation.ISiKOrganisationFachbteilung o-- ISiK_Terminplanung.ISiKMedizinischeBehandlungseinheit : .providedBy 0..1



ISiK_Basis --up[hidden]->   ISiK_Terminplanung



/'
together ISiK_Terminplanung {

   class ISiKKalender <Schedule><<(P,#8DA5C4)>>{
   extension : **ScheduleName**
   |_ (All Slices)
      |_ <s> extension </s>
      |_ KalenderName : **Extension**
   active
   serviceType
   specialty
   |_ Fachrichtung : **IHEXDSauthorSpeciality**
   actor : Reference ( **Patient** | **Practitioner** | PractitionerRole | \n\t**RelatedPerson** | Device | HealthcareService | Location)
   |_ identifier
   |_ display
   |_ Akteur : Reference (**Practitioner** | HealthcareService)
      |_ reference
   }

   class ISiKMedizinischeBehandlungseinheit <HealthcareService><<(P,#8DA5C4)>>{
   active
   type
   specialty
   |_ Fachrichtung : **IHEXDSauthorSpeciality**
   name
   }

   class ISiKNachricht <Communication><<(P,#8DA5C4)>>{
   inResponseTo : Reference (Communication)
   status
   subject : Reference ( **Patient** )
   sent
   recipient : Reference ( Device | Organization | **Patient** | **Practitioner** | \n\tPractitionerRole | **RelatedPerson** | Group | CareTeam | HealthcareService)
   |_ identifier
   |_ display
   |_ ISiKRecipient : Reference ( **Practitioner** | HealthcareService)
      |_ reference
   sender : Reference ( Device | Organization | **Patient** | **Practitioner** | \n\tPractitionerRole | **RelatedPerson** | HealthcareService)
   |_ reference
   payload : BackboneElement
   |_ content[x]
      |_ contentString
      |_ contentAttachment
         |_ contentType
         |_ <s>data</s>
         |_ url
         |_ creation
   }

   class ISiKTermin <Appointment><<(P,#8DA5C4)>>{

   }

   class ISiKTerminblock <Slot><<(P,#8DA5C4)>>{

   }

   class ISiKTerminKontaktMitGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{

   }
}

'/