'@startuml usecases
'usecase Medikation as "
'    = Medikation
'    
'    ___
'    Some text
'    === Neu-Verordnung
'    Other text
'    === Anpassung
'    Information
'    === Abgabe
'"
'@enduml

@startuml usecases
left to right direction
'skinparam packageStyle cloud
'skinparam linetype ortho

'actor :FHIR Repository: as DB << Application >>
actor :Heilberufler:
actor :Versicherter:
:FHIR Repository: as FhirRepo << Technical User >>
:Client: as Client << Technical User >>

storage gnrlUC as "Allgemein" {
    (Versorgung)
    (Administration)
    (Digitalisierung)
    (Dokumentation)
    (Abrechnung)
    (Strukturierung)
    (Organisationsstruktur)
    (Archivierung)
    (Delegation)
    (Konsultation)
    (Transparenz)
    storage patientUC as "Patienten-Management"{
        (Aufnahme) 
        (Behandlungs-Journey)
        (Entlassung)
        (Überleitung)
        (Information)
        (Einbeziehung \nAngehöriger)
        (Einsichtnahme)
    }
}

storage adverseUC as "Adverse Use Cases" {
    storage (Verwechslung){
        (Patient)
        (Fall)
        (Diagnose)
        (Ort-Zeit)
    }
    (Merhfachdokumentation)
    (Dokumentationslücken)
    (Nicht-Verfügbarkeit)
    (Verlust)
}

storage techUC as "Technical Use Case" {
    (Synchronisation)
    (Performance & \nDatensparsamkeit)
    (Wechsel führendes System)
    (Kommunikation)
    (Eindeutigkeit)
    (Grundlagen-Ressourcen)
}



Heilberufler --> gnrlUC
Versicherter --> patientUC

FhirRepo --> techUC
Client --> techUC

'fncts --> adverseUC : mitigates
'fncts --> gnrlUC : enables
@enduml