@startuml
scale max 700 width
box "ISiK konformes System" #LightBlue
participant FormularLauncher
participant FormularDatenQuelle
end box
box "FormularRenderer" #LightGreen
participant FormularRenderer
participant FormularDefinitionsVerwalter
end box
box "FormularExtraktor" #LightYellow
participant FormularExtraktor
end box
FormularLauncher -> FormularRenderer : Launch 
FormularRenderer <-> FormularDefinitionsVerwalter : FormularDefintionsVerwaltung 
FormularRenderer <-> FormularDatenQuelle :  FormularDatenVorbelegung 
FormularRenderer -> FormularRenderer : FormularRendering
FormularRenderer -> FormularRenderer : FormularDatenValidierung
group Option
  FormularRenderer <-> FormularExtraktor : FormularDatenExtraktion
end group
FormularRenderer -> FormularDatenQuelle : FormularDatenRückübermittlung
group Option
  FormularDatenQuelle <-> FormularExtraktor : FormularDatenExtraktion
end group
@enduml