@startuml
FormularRenderer -> FormularDatenBereitsteller : GET Patient
FormularRenderer -> FormularDatenBereitsteller : GET Encounter
FormularRenderer -> FormularDatenBereitsteller : SEARCH Observation
@enduml