id: ICU
canonical: https://gematik.de/fhir/isik
name: ISiKICUImplementationGuide
title: ISiK ICU
description: Dieser Implementierungsleitfaden spezifiziert eine Schnittstelle zur ISiK-konformen Umsetzung für Datenkommunikations-Workflows zur Verlegung zwischen der Intensivstation (Intensive Care Unit - ICU) und der Normalstation im Krankenhaus.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ballot
license: CC0-1.0
publisher: gematik GmbH

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.uv.ips: 2.0.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.6.0-ballot2
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.4
  de.gematik.ti: 1.1.1
  
pages:
  index.md:
    title: Einführung
  Akteure.md:
    title: Akteure
  Festlegungen.md:
    title: Festlegungen
  ProzesseUndWorkflows.md:
    title: Prozesse und Workflows
  ReleaseNotes.md:
    title: Release Notes
  UseCases.md:
    title: Use Case - Übergang zwischen Akut- und Normalversorgung
  artifacts-isik.md:  
    title: FHIR-Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases: UseCases.html
  Akteure: Akteure.html
  Prozesse und Workflows: ProzesseUndWorkflows.html
  Festlegungen: Festlegungen.html
  FHIR-Artefakte: artifacts-isik.html

parameters:
  display-warnings: true
  path-expansion-params: ../../input/resources/Parameters-exp-params.json
  special-url:
    - http://example.org/fhir/CodeSystem/TestKatalog
    - http://example.org/fhir/ValueSet/TestValueSet

#und ggfs noch:
#  no-narrative: true