@startuml
!include termin-components.puml

' zusätzliche Komponenten oder andere Beziehungen für Variante 1

component "Clinical Data Repository" as CDR {
  [Termin-Repository]
}

CDR --> [Termin-Repository]

@enduml