' Zweck: diese Uml zeigt die grundlegenden Komponenten und deren Beziehungen

package "Core Components" {
  [Termin-Repository]
  [Termin-Requestor]
  [Termin-Consumer]
}

[Termin-Requestor] --> [Termin-Repository]
[Termin-Consumer] --> [Termin-Repository]
@enduml