id: formular
canonical: https://gematik.de/fhir/isik/ImplementationGuide/ISiK-Formularmodul
name: ISiK-Formularmodul
title: ISiK Formularmodul Implementation Guide
description: Implementation guide for the Formular module based on ISiK specifications.
status: active
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0-ballot
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.3
  de.gematik.ti: 1.1.1

  
pages:
  index.md:
    title: Einführung
  Ziele.md:
    title: Ziele
  ReleaseNotes.md:
    title: Release Notes
  Festlegungen.md:
    title: Übergreifende Festlegungen
  AkteureOhneCpS.md:
    title: Festlegungen Akteure ohne CapabilityStatement
  Akteure.md:
    title: Akteure
  FunktionenInteraktionen.md:
    title: Funktionen und Interaktionen
  Spezifikationen_Beispielszenarien.md:
    title: Beispielszenarien
  Spezifikationen_BestPractice.md:
    title: Best Practice für FormularDefinitionen
  Spezifikationen_Begriffsdefinitionen.md:
    title: Begriffsdefinitionen
  Extensions.md:
    title: Extensions
  artifacts.md:  
    title: FHIR-Artefakte

#TODO Beispiele

menu:
  Einführung: index.html
  Ziele: Ziele.html
  Release Notes: ReleaseNotes.html
  Festlegungen: 
    Übergreifende Festlegungen: Festlegungen.html
    Festlegungen Akteure ohne CapabilityStatement: AkteureOhneCpS.html
  Spezifikationen:
    Akteure: Akteure.html
    Funktionen und Interaktionen: FunktionenInteraktionen.html
    Beispielszenarien: Spezifikationen_Beispielszenarien.html
    Best Practice für FormularDefinitionen: Spezifikationen_BestPractice.html
    Begriffsdefinitionen: Spezifikationen_Begriffsdefinitionen.html
    Extensions: extensions.html
  FHIR-Artefakte: artifacts.html
 

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true