id: formular
canonical: https://gematik.de/fhir/isik
name: FormularImplementationGuide
title: Formular Implementation Guide
description: Implementation guide for the Formular module based on ISiK specifications.
status: active
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0-ballot
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.3
  de.gematik.ti: 1.1.1

  
pages:
  index.md:
    title: Index
  Ziele.md:
    title: Ziele
  ReleaseNotes.md:
    title: Release Notes
  Index_Festlegungen.md:
    title: Festlegungen
  Kompatibilitaet.md:
    title: Kompatibilität
  Uebergreifende_Festlegungen.md:
    title: Übergreifende Festlegungen
  Index_Spezifikationen.md:
    title: Spezifikationen
  Index_AkteurOrdner.md:
    title: Akteure
  Akteure_FormularLauncher.md:
    title: FormularLauncher
  Akteure_FormularDatenQuelle.md:
    title: FormularDaten-Quelle
  Akteure_FormularDefinitionsErsteller.md:
    title: FormularDefinitions-Ersteller
  Akteure_FormularDefinitionsVerwalter.md:
    title: FormularDefinitions-Verwalter
  Akteure_FormularRenderer.md:
    title: FormularRenderer
  Index_FunktionenInteraktionen.md:
    title: Funktionen und Interaktionen
  FunktionenInteraktionen_Launch.md:
    title: Launch
  FunktionenInteraktionen_FormularDefinitionsVerwaltung.md:
    title: FormularDefinitions-Verwaltung
  FunktionenInteraktionen_FormularDatenVorbelegung.md:
    title: FormularDaten-Vorbelegung
  FunktionenInteraktionen_FormularDatenValidierung.md:
    title: FormularDaten-Validierung
  FunktionenInteraktionen_FormularDatenExtraktion.md:
    title: FormularDaten-Extraktion
  FunktionenInteraktionen_FormularDatenRueckuebermittlung.md:
    title: FormularDaten-Rückübermittlung
  Spezifikationen_Beispielszenarien.md:
    title: Beispielszenarien
  Spezifikationen_BestPractice.md:
    title: Best Practice für FormularDefinitionen
  Spezifikationen_Begriffsdefinitionen.md:
    title: Begriffsdefinitionen
  Extensions.md:
    title: Extensions
  artifacts.md:  
    title: FHIR-Artefakte

#TODO Beispiele

menu:
  Index: Index.html
  Ziele: Ziele.html
  Release Notes: ReleaseNotes.html
  Festlegungen:
    Index: Index_Festlegungen.html
    Kompatibilität: Kompatibilitaet.html
    Übergreifende Festlegungen: Uebergreifende_Festlegungen.html
  Spezifikationen:
    Index: Index_Spezifikationen.html
    AkteureOrdner:
      Index: Index_AkteurOrdner.html
      FormularLauncher: Akteure_FormularLauncher.html
      FormularDatenQuelle: Akteure_FormularDatenQuelle.html
      FormularDefinitionsErsteller: Akteure_FormularDefinitionsErsteller.html
      FormularDefinitionsVerwalter: Akteure_FormularDefinitionsVerwalter.html
      FormularRenderer: Akteure_FormularRenderer.html
    FunktionenInteraktionen:
      Index: Index_FunktionenInteraktionen.html
      Launch: FunktionenInteraktionen_Launch.html
      FormularDefinitions-Verwaltung: FunktionenInteraktionen_FormularDefinitionsVerwaltung.html
      FormularDaten-Vorbelegung: FunktionenInteraktionen_FormularDatenVorbelegung.html
      FormularDaten-Validierung: FunktionenInteraktionen_FormularDatenValidierung.html
      FormularDaten-Extraktion: FunktionenInteraktionen_FormularDatenExtraktion.html
      FormularDaten-Rückübermittlung: FunktionenInteraktionen_FormularDatenRueckuebermittlung.html
    Beispielszenarien: Spezifikationen_Beispielszenarien.html
    Best Practice für FormularDefinitionen: Spezifikationen_BestPractice.html
    Begriffsdefinitionen: Spezifikationen_Begriffsdefinitionen.html
    Extensions: extensions.html
  FHIR-Artefakte: artifacts.html
 

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true