sequenceDiagram
    actor TXB
    participant D as DETECT
    participant F as FHIR-Server

    D->>F:/location?type=wa
    F-->>D:Location

    TXB->>D: create notification settings for wards
    D->>D: extract: wardIds

    loop every 12 hours
        rect rgb(245, 245, 245)
            note left of D: Featch relevant Cases
            D->>F: /encounter?location=wardIds&status=in-progress
            F-->>D: List of Encounter
            D->>D: extract: PIDs, CaseIds
            D->>F: /Observation?patient=PIDs[]&code=LoincGCS,LoincRass,LoincPupille
            F-->>D: List of Observation
        end
        rect rgb(255, 245, 235)
            note left of D: Fetch optional Parameter
            D->>D: extract: relevantPIDs
            D->>F: /Patient?_id=relevantPIDs
            F-->>D: List of Patient
            D->>F: /Observation?patient=relevantPIDs&code=NATRIUM,ICP,CPP&date=TODAY-48h
            F-->D: List of Observation
            D->>F: /Procedure?patient=relevantPIDs&code=VENT,REANIMATION
            F-->>D: List of Procedure
        end
        D->>D: Create Notifications
        D->>TXB: Send Notification
    end