id: connect.test.ig
canonical: http://example.org/fhir/test-connect-ig
name: TestImplementationGuide
title: Test Implementation Guide
description: A test implementation guide for validating the local FHIR IG Publisher environment
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: STU1
license: CC0-1.0
publisher: Test Organization

applyExtensionMetadataToRoot: false
dependencies:
 
  
pages:
  index.md:
    title: Einführung
  Akteure.md:
    title: Akteure
  Anforderungsuebersicht.md:
    title: Anforderungsübersicht 
  AutoProvisioning.md:
    title: Auto Provisioning
  BackendServices.md:
    title: Backend Services
    Schritt1RegistrierungBackendService.md:
    Schritt2AbrufSmartConfiguration.md:
    Schritt3AbrufAccessToken.md:
    Schritt4FHIRRestInteraktion.md:
  Conformance.md:
    title: Conformance
  ConformanceScopesKontexte.md:
    title: Conformance Scopes und Kontexte
  ConformanceSmartCapabilities.md:
    title: Conformance Smart Capabilities 
  ISiKAutorisierung.md:
    title: Autorisierung
  ISiKundSMART.md:
    title: "ISiK Connect und Smart-on-FHIR"
  KompatibilitaetDerGematikSpezifikation.md:
    title: "Festlegungen zur Kompatibilität der gematik-Spezifikation"
  Kontext.md:
    title: ISiK Connect Kontext
  ReleaseNotes.md:
    title: Release Notes
  Schritt1RegistrierungClient.md:
    title: "Schritt 1: Registrierung eines Clients"
  Schritt2ClientAutorisierung.md:
    title: "Schritt 2: Client Autorisierung"
  Schritt3EvaluierungAutorisierungsanfragen.md:
    title: "Schritt 3: Evaluierung von Autorisierungsanfragen"
  Schritt4AustauschAutorisierungscodesZugangstoken.md:
    title: "Schritt 4: Austausch von Autorisierungscodes gegen Zugangstoken"
  Schritt5FHIRRestInteraktion.md:
    title: "Schritt 5: FHIR REST Interaktion"
  Schritt6RefreshToken.md:
    title: "Schritt 6: Refresh Token & Revocation"
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen und Kompatibilität
  


menu:
  Einführung: Einfuehrung.html
  Release Notes: ReleaseNotes.html
  Akteure: Akteure.html
  Festlegungen:
    UebergreifendeFestlegungen: UebergreifendeFestlegungen.html
    Kompatibilitaet der Gematik Spezifikation: KompatibilitaetDerGematikSpezifikation.html
  Kontext Smart-on-FHIR: 
    Kontext: Kontext.html
    Smart on FHIR - App Launch: ISiKundSMART.html
    Smart on FHIR - Backend Services: BackendServices.html
    Auto Provisioning: AutoProvisioning.html
  Festlegungen Connect:
    Smart Capabilities: ConformanceSmartCapabilities.html
    Scopes und Compartments: ConformanceScopesKontexte.html
    Autorisierung: ISiKAutorisierung.html
  Anforderungsübersicht: Anforderungsuebersicht.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true