id: connect
canonical: http://example.org/fhir/isik
name: ConnectISiKImplementationGuide
title: ISiK Connect Implementierungsleitfaden
description: Implementierungsleitfaden für ISiK Connect, der die Spezifikationen für die Integration mittels Smart-on-FHIR von FHIR-basierten Anwendungen in Krankenhäusern beschreibt.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: STU1
license: Apache-2.0
publisher: 
  name: gematik GmbH
  url: https://www.gematik.de

applyExtensionMetadataToRoot: false
dependencies:
 
  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  Akteure.md:
    title: Akteure
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen und Kompatibilität  
  KompatibilitaetDerGematikSpezifikation.md:
    title: "Festlegungen zur Kompatibilität der gematik-Spezifikation"
  Kontext.md:
    title: ISiK Connect Kontext
  ISiKundSMART.md:
    title: "ISiK Connect und Smart-on-FHIR"
  BackendServices.md:
    title: Backend Services
  AutoProvisioning.md:
    title: Auto Provisioning
  ConformanceSmartCapabilities.md:
    title: "Conformance: Smart Capabilities"
  ConformanceScopesKontexte.md:
    title: "Conformance: Scopes und Kontexte"
  ISiKAutorisierung.md:
    title: Autorisierung
  Anforderungsuebersicht.md:
    title: Anforderungsübersicht  


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Akteure: Akteure.html
  Festlegungen:
    UebergreifendeFestlegungen: UebergreifendeFestlegungen.html
    Kompatibilitaet der Gematik Spezifikation: KompatibilitaetDerGematikSpezifikation.html
  Kontext Smart-on-FHIR: 
    Kontext: Kontext.html
    Smart on FHIR - App Launch: ISiKundSMART.html
    Smart on FHIR - Backend Services: BackendServices.html
    Auto Provisioning: AutoProvisioning.html
  Festlegungen Connect:
    Smart Capabilities: ConformanceSmartCapabilities.html
    Scopes und Compartments: ConformanceScopesKontexte.html
    Autorisierung: ISiKAutorisierung.html
  Anforderungsübersicht: Anforderungsuebersicht.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true