id: dokumentenaustausch
canonical: https://gematik.de/fhir/isik
name: ISiKDokumentenaustauschImplementationGuide
title: ISiK Dokumentenaustausch
description: Dieser Implementierungsleitfaden spezifiziert eine ISiK-konforme Umsetzung des Dokumentenaustauschs im Krankenhaus.
status: active
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: Apache-2.0
publisher: 
  name: gematik GmbH
  url: https://www.gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  # hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.5.4
  de.ihe-d.terminology: 3.0.1
  dvmd.kdl.r4: 2025.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 3.0.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Einführung
  Abgrenzung-Basis.md:
    title: Abgrenzung zum Basismodul
  Akteure.md:
    title: Akteure
  Dokumentenabfrage.md:
    title: Dokumentenabfrage
  ErzeugenVonMetadaten.md:
    title: Erzeugen von Metadaten
  Interaktion-Dokumentenbereitstellung.md:
    title: Interaktion Dokumentenbereitstellung
  Interaktionen.md:
    title: Interaktionen
  Kompatibilitaet.md:
    title: Kompatibilität
  ReleaseNotes.md:
    title: Release Notes
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen
  Update.md:
    title: Update
  UseCaseUndAkteure.md:
    title: Use Case und Akteure
  artifacts.md:
    title: FHIR-Artefakte



menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases und Akteure:
    Akteure: Akteure.html
    Interaktionen: Interaktionen.html
    "Kompatibilität und Interoperabilität mit IHE (MHD und XDS)": Kompatibilitaet.html
    "Abgrenzung zu ISiK Basis bei Kommunikation *strukturierter* Daten": Abgrenzung-Basis.html
  Festlegungen:
    Übergreifende Festlegungen: UebergreifendeFestlegungen.html
    "Interaktion: Dokumentenbereitstellung": Interaktion-Dokumentenbereitstellung.html
    "Interaktion: Dokumentenabfrage und -Zugriff": Dokumentenabfrage.html
    "Interaktion: Update von Metadaten": Update.html
    "Interaktion: Erzeugen von Metadaten": ErzeugenVonMetadaten.html
  FHIR-Artefakte: artifacts.html
 
parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true