id: labor
canonical: https://gematik.de/fhir/isik
name: ISiKLaborImplementationGuide
title: ISiK Labor Implementierungsleitfaden
description: Implementation guide for the Labor module based on ISiK specifications.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
   hl7.fhir.extensions.r5: 4.0.1
   hl7.fhir.uv.ips: 1.1.0
   hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
   de.basisprofil.r4: 1.5.4
   de.ihe-d.terminology: 3.0.1
   dvmd.kdl.r4: 2025.0.1
   ihe.formatcode.fhir: 1.4.0

  
  
pages:
  index.md:
    title: Einführung
  AMTS.md:
    title: AMTS
  BestaetigungsrelevanteSysteme.md:
    title: Bestätigungsrelevante Systeme
  InteraktionenUndSearchTypes.md:
    title: Interaktionen und Search Types
  Kompatibilitaet.md:
    title: Kompatibilität
  ReleaseNotes.md:
    title: Release Notes
  RestApi.md:
    title: REST-API
  UebergreifendeFestlegungen.md:
    title: Übergreifende Festlegungen
  UebergreifendeUseCases.md:
    title: Übergreifende Use Cases
  UeberleitungIntensiv.md:
    title: Überleitung Intensiv
  artifacts-isik.md:
    title: Artefakte


menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Festlegungen:
    Übergreifende Festlegungen: UebergreifendeFestlegungen.html
    Bestätigungsrelevante Systeme: BestaetigungsrelevanteSysteme.html
    REST-API Grundlagen: RestApi.html
    Kompatibilität: Kompatibilitaet.html
  Use Cases:
    Übergreifende Use Cases: UebergreifendeUseCases.html
    Arzneimitteltherapiesicherheit (AMTS): AMTS.html
    Überleitung Intensiv: UeberleitungIntensiv.html
    Interaktionen und Search Types: InteraktionenUndSearchTypes.html
  FHIR-Artefakte: artifacts-isik.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true