ValueSet: VS_MII_ICU_Code_Monitoring_und_Vitaldaten_LOINC
Id: vs-mii-icu-code-monitoring-und-vitaldaten-loinc
Title: "VS MII ICU Code Monitoring und Vitaldaten [LOINC]"
Description: "Dieses ValueSet enthält Codes für Vitaldaten sowie Daten aus dem Patientenmonitoring."
* insert Meta
* $loinc#8867-4 "Heart Rate"
* $loinc#8480-6 "Systolic blood Pressure"
* $loinc#8478-0 "Mean blood Pressure"
* $loinc#8462-4 "Diastolic blood pressure"
* $loinc#60985-9 "Central venous pressure (CVP)"
* $loinc#8440-0 "Pulmonary artery Systolic blood pressure"
* $loinc#8414-5 "Pulmonary artery Mean blood pressure"
* $loinc#8385-7 "Pulmonary artery Diastolic blood pressure"
* $loinc#75994-4 "Pulmonary artery wedge pressure"
* $loinc#8737-9 "Left ventricular Cardiac output by Indicator dilution"
* $loinc#8751-0 "Left ventricular Cardiac index by Indicator dilution"
* $loinc#8741-1 "Left ventricular Cardiac output"
* $loinc#75919-1 "Left ventricular Cardiac index"
* $loinc#8837-7 "Systemic vascular Resistance index"
* $loinc#8834-4 "Pulmonary vascular Resistance index"
* $loinc#8771-8 "Left ventricular Stroke volume by Indicator dilution"
* $loinc#8791-6 "Left ventricular Stroke volume index by Indicator dilution"
* $loinc#20562-5 "Left ventricular Stroke volume"
* $loinc#76297-1 "Left ventricular Stroke volume index"
* $loinc#8329-5 "Body temperature - Core"
* $loinc#59408-5 "Oxygen saturation in Arterial blood by Pulse oximetry"
* $loinc#59418-4 "Oxygen saturation in Blood Postductal by Pulse oximetry"
* $loinc#59407-7 "Oxygen saturation in Blood Preductal by Pulse oximetry"
* $loinc#60956-0 "Intracranial pressure (ICP)"
* $loinc#8404-6 "Left ventricular Intrachamber mean pressure"
* $loinc#8406-1 "Right ventricular Intrachamber mean pressure"
* $loinc#8430-1 "Left ventricular Intrachamber systolic pressure"
* $loinc#8432-7 "Right ventricular Intrachamber systolic pressure"
* $loinc#8375-8 "Left ventricular Intrachamber diastolic pressure"
* $loinc#8377-4 "Right ventricular Intrachamber diastolic pressure"
* $loinc#60998-2 "Right atrial pressure Systolic"
* $loinc#60989-1 "Left atrial pressure Systolic"
* $loinc#8399-8 "Left atrial Intrachamber mean pressure"
* $loinc#8400-4 "Right atrial Intrachamber mean pressure"
* $loinc#75933-2 "Left atrial pressure Diastolic"
* $loinc#60997-4 "Right atrial pressure Diastolic"
* $loinc#29463-7 "Body weight"
* $loinc#50064-5 "Ideal body weight"
* $loinc#8302-2 "Body height"
* $loinc#8303-0 "Body height [Percentile]"
* $loinc#8336-0 "Body weight [Percentile] Per age"
* $loinc#8333-7 "Tympanic membrane temperature"
* $loinc#8332-9 "Rectal temperature"
* $loinc#60836-4 "Esophageal temperature"
* $loinc#8334-5 "Body temperature - Urinary bladder"
* $loinc#8328-7 "Axillary temperature"
* $loinc#8331-1 "Oral temperature"
* $loinc#60834-9 "Blood temperature"
* $loinc#60955-2 "Airway temperature"
* $loinc#61009-7 "Myocardial temperature"
* $loinc#76010-8 "Nasal temperature"
* $loinc#8310-5 "Body temperature"
* $loinc#60838-0 "Nasopharyngeal temperature"
* $loinc#104063-3 "Body temperature - Groin"
