' Define the desired detail level before @startuml
' For example, set in command line or file: !define DETAIL_HIGH

@startuml

[APIGateway]  as APIGateway
component KIS  {

  Component "TEST KOMPONENTE" as TEST

  component "Terminplanung" {
    [Termin-Repository (KIS-Modul)] as TerminKIS
    portin iBookAppointments
    } 
  ' component "PDMS-Modul" as PDMSKISMODUL
  ' component "weiteres KIS-Modul" as KISMODUL
  component "Alerting und Notification Management \n (mittels Subscription - nicht normativ)" {
    ' Diese Komponente bedingt, das das CDR event-getriggered bzw. über einen livestream aktualisiert wird
    portin  iSubscribeStammdaten
    }

  portin iProvideBasicData
  }

TEST --> APIGateway : test

@enduml