name: Unzip and Process

on:
    workflow_dispatch:  # Ermöglicht die manuelle Auslösung des Workflows
    push:
        branches:
            - gh-pages
            - feature/automate-gh*
        paths:
            - IG/isik-*.zip  # Trigger auf das Hinzufügen einer ZIP-Datei im IG-Ordner
    

jobs:
  unzip-and-process:
    runs-on: ubuntu-latest  # Verwende die neueste Ubuntu-Umgebung

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Klone das Repository, um auf den Code zuzugreifen

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Installiere die neueste Python-Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4  # Installiere die Abhängigkeit für HTML-Verarbeitung

      - name: Unzip file
        id: unzip
        run: |
          # Bestimme die ZIP-Datei und enpacke sie in einen Versionsordner namens new-IG
          ZIP_FILE=$(ls IG/isik-*.zip)
          unzip "$ZIP_FILE" -d new-IG
          #lese die Versionsnummer aus der HTML-Datei "ImplementationGuide-markdown-Einfuehrung.html" im neuen Ordner
          VERSION=$(grep -oP '(?<=Version: )\d+\.\d+\.\d+' new-IG/ImplementationGuide-markdown-Einfuehrung.html)
          #benenne den Ordner um in die Versionsnummer und gib die Versionsnummer aus
          mv new-IG "$VERSION"
          #falls die Versionsnummer nicht gefunden wird, gebe eine Fehlermeldung aus und exitiere
          if [ -z "$VERSION" ]; then
            echo "Version number not found in ImplementationGuide-markdown-Einfuehrung.html"
            exit 1
          fi
          echo "Unzipped version: $VERSION"
          # Setze die Versionsnummer als Variable, die später für den python argument input verwendet wird
          echo "::set-env name=VERSION::$VERSION"

      - name: Remove packages folder
        run: |
          rm -rf "$VERSION/packages"  # Entferne den packages-Ordner aus dem Versionsordner

      - name: Run Python script
        run: |
          python scripts/update_index.py "${{ env.VERSION }}"  # Führe das benutzerdefinierte Python-Skript mit der Versionsnummer als Argument aus

      - name: Commit changes
        run: |
          # Konfiguriere Git-Benutzerinformationen für den Commit
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "$VERSION"  # Füge den Versionsordner zu den Änderungen hinzu
          git commit -m "Processed ZIP file: $ZIP_FILE"  # Erstelle den Commit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Update from IG folder'  # Titel des Pull-Requests
          body: 'Automated PR: Processed new IG-ZIP file.'  # Beschreibung des Pull-Requests
          base: gh-pages  # Ziel-Branch für den Pull-Request
          branch: update-from-zip  # Erstelle einen neuen Branch für die Änderungen
