id: amts
canonical: https://gematik.de/fhir/isik
name: AMTSISiKImplementationGuide
title: AMTS ISiK Implementierungsleitfaden
description: Implementierung für das AMTS-Modul basierend auf ISiK-Spezifikationen.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ballot
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.uv.ips: 2.0.0
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0
  de.basisprofil.r4: 1.6.0-ballot2
  de.ihe-d.terminology: 3.0.1
  ihe.formatcode.fhir: 1.4.0
  hl7.fhir.uv.sdc: 4.0.0
  de.gematik.terminology: 1.0.6
  de.fhir.medication: 1.0.4
  de.gematik.ti: 1.1.1
  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  Akteure.md:
    title: "Stakeholder, User und weitere Systeme"
  UseCases.md:
    title: Use Cases
  Festlegungen.md:
    title: Festlegungen
  artifacts-isik.md:
    title: FHIR-Artefakte
  
  

menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases und Akteure: 
    Stakeholder, User und weitere Systeme: Akteure.html
    Use Cases: UseCases.html
  Festlegungen: Festlegungen.html 
  FHIR-Artefakte: artifacts-isik.html

parameters:
  display-warnings: true
  path-expansion-params: Parameters-exp-params.json
  special-url:
    - http://example.org/fhir/CodeSystem/TestKatalog