id: amts
canonical: https://gematik.de/fhir/isik
name: AMTSISiKImplementationGuide
title: AMTS ISiK Implementation Guide
description: Implementation for the AMTS module based on ISiK specifications.
status: draft
version: 6.0.0-rc
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: STU1
license: Apache-2.0
publisher:
  name: gematik GmbH
  url: https://gematik.de

applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.5.4 
  ihe.formatcode.fhir: 1.4.0
  de.gematik.terminology: 1.0.6
  
pages:
  index.md:
    title: Einführung
  ReleaseNotes.md:
    title: Release Notes
  Akteure.md:
    title: "Stakeholder, User und weitere Systeme"
  UseCases.md:
    title: Use Cases
  Festlegungen.md:
    title: Festlegungen
  artifacts-isik.md:
    title: FHIR-Artefakte
  
  

menu:
  Einführung: index.html
  Release Notes: ReleaseNotes.html
  Use Cases und Akteure: 
    Stakeholder, User und weitere Systeme: Akteure.html
    Use Cases: UseCases.html
  Festlegungen: Festlegungen.html 
  FHIR-Artefakte: artifacts-isik.html

parameters:
  no-validate: true

#und ggfs noch:
#  no-narrative: true